AWSTemplateFormatVersion: 2010-09-09
Description:
  Account = uk-cti-contentdelivery-dev.
  This template deploys a VPC, private and connect subnets spread across three Availability Zones with individual route tables.


Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: dev-cntdel-euw2-vpc-03

  VpcCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Description: IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.52.61.0/24

  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.52.61.0/26

  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.52.61.64/26

  PrivateSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Description: Please enter the IP range (CIDR notation) for the private subnet in the third Availability Zone
    Type: String
    Default: 10.52.61.128/26

#  PrivateSubnet4CIDR:
#    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
#    Description: Please enter the IP range (CIDR notation) for the private subnet in the third Availability Zone
#    Type: String
#    Default: 10.52.59.128/27
#
#  PrivateSubnet5CIDR:
#    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
#    Description: Please enter the IP range (CIDR notation) for the private subnet in the third Availability Zone
#    Type: String
#    Default: 10.52.59.160/27


  ConnectSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.52.61.208/28

  ConnectSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.52.61.224/28

  ConnectSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Description: Please enter the IP range (CIDR notation) for the private subnet in the third Availability Zone
    Type: String
    Default: 10.52.61.240/28

#  VgwASN:
#    Description: BGP ASN for VGW
#    Type: String
#    Default: 65061

###################################################

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName},
        - Key: 'tgw-attach'
          Value: 'tgw-attach'

  ConnectSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref ConnectSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dev-cntdel-az1-connectsubnet-01
        - Key: 'tgw-attach'
          Value: 'True'

  ConnectSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref ConnectSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dev-cntdel-az2-connectsubnet-01
        - Key: 'tgw-attach'
          Value: 'True'

  ConnectSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: !Ref ConnectSubnet3CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dev-cntdel-az3-connectsubnet-01
        - Key: 'tgw-attach'
          Value: 'True'


  ConnectRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: dev-cntdel-connectrtb-01

  ConnectSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ConnectRouteTableA
      SubnetId: !Ref ConnectSubnet1

  ConnectSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ConnectRouteTableA
      SubnetId: !Ref ConnectSubnet2

  ConnectSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ConnectRouteTableA
      SubnetId: !Ref ConnectSubnet3


  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dev-cntdel-az1-privatesubnet-01

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dev-cntdel-az2-privatesubnet-01

  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 2, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet3CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dev-cntdel-az3-privatesubnet-01

#  PrivateSubnet4:
#    Type: AWS::EC2::Subnet
#    Properties:
#      VpcId: !Ref VPC
#      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
#      CidrBlock: !Ref PrivateSubnet4CIDR
#      MapPublicIpOnLaunch: false
#      Tags:
#        - Key: Name
#          Value: dev-cntdel-az1-privatesubnet-02

#  PrivateSubnet5:
#    Type: AWS::EC2::Subnet
#    Properties:
#      VpcId: !Ref VPC
#      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
#      CidrBlock: !Ref PrivateSubnet5CIDR
#      MapPublicIpOnLaunch: false
#      Tags:
#        - Key: Name
#          Value: dev-cntdel-az2-privatesubnet-02
#
  PrivateRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: dev-cntdel-privatertb-01
        - Key: 'tgw-attach'
          Value: 'True'

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableA
      SubnetId: !Ref PrivateSubnet1


  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableA
      SubnetId: !Ref PrivateSubnet2

  PrivateSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableA
      SubnetId: !Ref PrivateSubnet3

#  PrivateSubnet4RouteTableAssociation:
#    Type: AWS::EC2::SubnetRouteTableAssociation
#    Properties:
#      RouteTableId: !Ref PrivateRouteTableA
#      SubnetId: !Ref PrivateSubnet4
#
#  PrivateSubnet5RouteTableAssociation:
#    Type: AWS::EC2::SubnetRouteTableAssociation
#    Properties:
#      RouteTableId: !Ref PrivateRouteTableA
#      SubnetId: !Ref PrivateSubnet5

#  Vgw:
#    Type: AWS::EC2::VPNGateway
#    Properties:
#      AmazonSideAsn: !Ref VgwASN
#      Tags:
#        - Key: Name
#          Value: dev-cntdel-euw2-vgw-02
#      Type: ipsec.1

#  VgwAttachment:
#    Type: AWS::EC2::VPCGatewayAttachment
#    Properties:
#      VpcId: !Ref VPC
#      VpnGatewayId: !Ref Vgw

#  VgwRoutePropagation:
#    Type: AWS::EC2::VPNGatewayRoutePropagation
#    DependsOn: VgwAttachment
#    Properties:
#      RouteTableIds:
#        - !Ref PrivateRouteTableA
#      VpnGatewayId: !Ref Vgw

  S3VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Statement:
        - Action: "*"
          Effect: Allow
          Resource: "*"
          Principal: "*"
      RouteTableIds:
      - !Ref PrivateRouteTableA
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !Ref VPC

##########################################

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

  ConnectSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref ConnectSubnet1

  ConnectSubnet2:
    Description: A reference to the public subnet in the 2nd Availability Zone
    Value: !Ref ConnectSubnet2

  ConnectSubnet3:
    Description: A reference to the public subnet in the 3rd Availability Zone
    Value: !Ref ConnectSubnet3

  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnet1

  PrivateSubnet2:
    Description: A reference to the private subnet in the 2nd Availability Zone
    Value: !Ref PrivateSubnet2

  PrivateSubnet3:
    Description: A reference to the private subnet in the 3rd Availability Zone
    Value: !Ref PrivateSubnet3

#  PrivateSubnet4:
#    Description: A reference to the 2nd private subnet in the 1st Availability Zone
#    Value: !Ref PrivateSubnet4

#  PrivateSubnet5:
#    Description: A reference to the 2nd private subnet in the 2nd Availability Zone
#    Value: !Ref PrivateSubnet5

  PrivateRouteTable:
    Description: A reference to the private subnets route table
    Value: !Ref PrivateRouteTableA

  ConnectRouteTable:
    Description: A reference to the connect subnets route table
    Value: !Ref ConnectRouteTableA

#  Vgw:
#    Description: Created Vgw
#    Value: !Ref Vgw

  S3GWVpcEndpoint:
    Description: Created S3 gateway endpoint
    Value: !Ref S3VpcEndpoint
